import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function MetaData(){
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

function Navigation(){
  return (
    <nav>
        <div>
         <a href="#">Logo</a>
        </div>

        <div>
          <ul>
            <a href="#">Register</a>
          </ul>
          <ul>
            <a href="#">Sign In</a>
          </ul>
        </div>
      </nav>
  );
}

function CallToAction(){
  return (
    <h1>Sign up for the resume builder. We have beans, greens, potaoes, tomtotes. <button>Try for free</button></h1>
  );
}

function Steps(){
  return <h2>this is the step</h2>;
}

function Prices(){
  return <h2>Money money money moeny</h2>;
}

function FooterBar(){
  return <footer>Footer element</footer>;
}

export default function Home() {
  return (
    <>
    <MetaData />
    <Navigation />
    <CallToAction />
    <Steps />
    <Prices />
    <FooterBar />
    </>
  )
}
